### ISSUE TITLE
Feature request: Subtract neighbors

### ISSUE THREAD

**Issue by tedmoorman** [Modesto-Escobar/netCoin-2.x#1]
First of all, congratulations on a super-impressive package! It's really well done. Thank you so much.

When I select a node_type in the Legend, more than just that node type also gets selected/highlighted. I also see the nearest neighbor of that node_type getting selected/highlighted. Neighbors that are more towards the outside of the network look more transparent/faded. I'm not sure whether this is intended.

If I select "Isolate", everything goes away except the node_type of interest. It would be nice to see the Links and all of the neighbors with a more transparent/faded look. The main node type of interest would hopefully still be selected/highlighted.

I'm wondering if a good solution to this would be to create a "Subtract neighbors" button. This would be like the "Add neighbors" button, but it would move the selection/highlighting in the opposite direction.

Hopefully what I'm describing is clear. If not, please let me know if you need me to add screen shots, etc. to better explain.

Thanks again for the great package and for considering this suggestion!

**Comment by Modesto-Escobar** [comment]
Done!
